name = "sigweb-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "sigweb-db"
database_id = "5a45e505-2413-4292-af4f-990c883778d7"

[vars]
ENV = "production"
API_KEY = "OTxzZ19Jb0dDOV9OVVBnXjV3VEJZN0o1dUxbTkZadlM="