import React from 'react';
import { 
  BookOpen, 
  Bell, 
  LogOut, 
  Search, 
  Settings, 
  Printer, 
  Plus, 
  ArrowLeft,
  ArrowRight,
  ChevronDown, 
  ChevronUp,
  Pencil, 
  Ban, 
  Eye, 
  X, 
  User, 
  Lock, 
  Check, 
  Trash2, 
  ShoppingCart, 
  FileText,
  Receipt,
  Minus, 
  Filter, 
  MoreVertical,
  CirclePlus,
  Car,
  ClipboardList,
  UserMinus,
  Fuel,
  TrendingUp,
  Clock,
  CheckCircle2,
  AlertCircle,
  XCircle,
  MoreHorizontal,
  Menu,
  Upload,
  Download,
  RefreshCw,
  Save,
  Send,
  Mail,
  Phone,
  MapPin,
  Calendar,
  DollarSign,
  BarChart3,
  Users,
  Building2,
  Package,
  Warehouse,
  Truck,
  Wrench,
  Shield,
  UserCog,
  FileCheck,
  History,
  Home,
  Layers,
  Database,
  HardDrive,
  Monitor,
  Wifi,
  Power,
  Sun,
  Moon,
  Star,
  Heart,
  ThumbsUp,
  ThumbsDown,
  Smile,
  Frown,
  Meh,
  HelpCircle,
  Info,
  AlertTriangle,
  Zap,
  Anchor,
  Aperture,
  Award,
  Gift,
  Grid,
  Hexagon,
  Image,
  Link,
  List,
  Mic,
  Move,
  Music,
  Paperclip,
  Pause,
  Play,
  Radio,
  Rewind,
  SkipBack,
  SkipForward,
  Tablet,
  Tag,
  Target,
  Terminal,
  Timer,
  ToggleLeft,
  ToggleRight,
  Triangle,
  Video,
  Volume2,
  VolumeX,
  Wallet,
  Webcam,
  Wind,
  Cloud,
  Droplets,
  Flame,
  Flower2,
  Leaf,
  Mountain,
  Waves
} from 'lucide-react';

const iconMap: Record<string, React.ElementType> = {
  'menu_book': BookOpen,
  'notifications': Bell,
  'logout': LogOut,
  'search': Search,
  'settings': Settings,
  'print': Printer,
  'add': Plus,
  'arrow_left': ArrowLeft,
  'arrow_right': ArrowRight,
  'chevron_left': ArrowLeft,
  'chevron_right': ArrowRight,
  'expand_more': ChevronDown,
  'expand_less': ChevronUp,
  'edit': Pencil,
  'block': Ban,
  'visibility': Eye,
  'close': X,
  'person': User,
  'person_off': UserMinus,
  'lock': Lock,
  'check': Check,
  'check_circle': CheckCircle2,
  'delete': Trash2,
  'shopping_cart': ShoppingCart,
  'receipt_long': Receipt,
  'remove': Minus,
  'filter_list': Filter,
  'add_circle': CirclePlus,
  'directions_car': Car,
  'assignment': ClipboardList,
  'local_gas_station': Fuel,
  'point_of_sale': TrendingUp,
  'schedule': Clock,
  'cancel': XCircle,
  'error': AlertCircle,
  'more_horiz': MoreHorizontal,
  'more_vert': MoreVertical,
  'menu': Menu,
  'upload': Upload,
  'download': Download,
  'refresh': RefreshCw,
  'save': Save,
  'send': Send,
  'email': Mail,
  'phone': Phone,
  'location_on': MapPin,
  'calendar_today': Calendar,
  'calendar_month': Calendar,
  'attach_money': DollarSign,
  'bar_chart': BarChart3,
  'group': Users,
  'groups': Users,
  'business': Building2,
  'inventory': Package,
  'inventory_2': Package,
  'warehouse': Warehouse,
  'local_shipping': Truck,
  'build': Wrench,
  'engineering': Wrench,
  'construction': Wrench,
  'security': Shield,
  'manage_accounts': UserCog,
  'fact_check': FileCheck,
  'description': FileText,
  'file_text': FileText,
  'history': History,
  'home': Home,
  'dashboard': Home,
  'layers': Layers,
  'storage': Database,
  'hard_drive': HardDrive,
  'computer': Monitor,
  'wifi': Wifi,
  'power_settings_new': Power,
  'light_mode': Sun,
  'dark_mode': Moon,
  'star': Star,
  'favorite': Heart,
  'thumb_up': ThumbsUp,
  'thumb_down': ThumbsDown,
  'sentiment_satisfied': Smile,
  'sentiment_dissatisfied': Frown,
  'sentiment_neutral': Meh,
  'help': HelpCircle,
  'info': Info,
  'warning': AlertTriangle,
  'trending_up': TrendingUp,
  'trending_down': TrendingUp,
  'flash_on': Zap,
  'anchor': Anchor,
  'camera': Aperture,
  'workspace_premium': Award,
  'card_giftcard': Gift,
  'grid_view': Grid,
  'category': Hexagon,
  'image': Image,
  'key': Link,
  'link': Link,
  'format_list_bulleted': List,
  'map': MapPin,
  'mic': Mic,
  'move': Move,
  'music_note': Music,
  'attachment': Paperclip,
  'pause': Pause,
  'play_arrow': Play,
  'radio': Radio,
  'fast_rewind': Rewind,
  'skip_previous': SkipBack,
  'skip_next': SkipForward,
  'stop': XCircle,
  'tablet': Tablet,
  'label': Tag,
  'track_changes': Target,
  'terminal': Terminal,
  'timer': Timer,
  'toggle_on': ToggleLeft,
  'toggle_off': ToggleRight,
  'change_history': Triangle,
  'umbrella': Anchor,
  'videocam': Video,
  'volume_up': Volume2,
  'volume_off': VolumeX,
  'account_balance_wallet': Wallet,
  'videocam_off': Webcam,
  'air': Wind,
  'cloud': Cloud,
  'water_drop': Droplets,
  'local_fire_department': Flame,
  'local_florist': Flower2,
  'grass': Leaf,
  'terrain': Mountain,
  'waves': Waves,
  'report_problem': AlertTriangle,
  'picture_as_pdf': FileText,
  'verified': CheckCircle2,
  'emoji_events': Award,
  'person_check': UserCog,
  'store': Package,
  'shield': Shield,
  'payments': DollarSign
};

interface IconProps {
  name: string;
  className?: string;
  size?: number;
  style?: React.CSSProperties;
}

export const MaterialIcon: React.FC<IconProps> = ({ name, className = '', size = 24, style }) => {
  const IconComponent = iconMap[name];
  
  if (!IconComponent) {
    return <span className={`material-symbols-outlined ${className}`} style={{ fontSize: size, ...style }}>{name}</span>;
  }
  
  return <IconComponent size={size} className={className} style={style} />;
};

export const iconComponents = iconMap;